### ISSUE TITLE
Error in Debian 9.6

### ISSUE THREAD

**Issue by samhae** [desbma/sysstat_mail_report#4]
Traceback (most recent call last):
  File "/usr/local/bin/sysstat_report.py", line 586, in <module>
    **plot_args[data_type])
  File "/usr/local/bin/sysstat_report.py", line 446, in plot
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('gnuplot',)' returned non-zero exit status 1

**Comment by desbma** [comment]
Output of `gnuplot -V`?
Did you run `sysstat_report.py` with `-v debug` to get the full error output?

**Comment by samhae** [comment]
gnuplot 5.0 patchlevel 5

2018-12-28 17:33:32,446 DEBUG Decompressing '/var/log/sysstat/sa27.xz' to '/tmp/sysstat_report_bfwo1c1n/sa27'...
2018-12-28 17:33:32,454 INFO Total amount of memory: 7987 MB
2018-12-28 17:33:32,454 DEBUG Speed of interface ens32: 1000 Mb/s
2018-12-28 17:33:32,454 INFO Maximum interface speed: 1000 Mb/s
2018-12-28 17:33:32,464 INFO Extracting LOAD data...
2018-12-28 17:33:32,472 INFO Generating LOAD TXT report...

gnuplot> set decimalsign locale;
                         ^
         line 0: Could not find requested locale


gnuplot> plot '/tmp/sysstat_report_bfwo1c1n/load.csv' using ($3+3600):7 with lines title 'ldavg-5';
                                                                                                  ^
         line 0: all points y value undefined!

Traceback (most recent call last):
  File "/usr/local/bin/sysstat_report.py", line 586, in <module>
    **plot_args[data_type])
  File "/usr/local/bin/sysstat_report.py", line 446, in plot
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('gnuplot',)' returned non-zero exit status 1

**Comment by desbma** [comment]
It seems you are either missing data to plot, or gnuplot can not parse it for some reason.

What is the output of `grep ldavg /var/log/sysstat/sar$(date --date="yesterday" +%Y%m%d)`

Also does `sadf -- -q` give you any output or error?

**Comment by samhae** [comment]
grep ldavg /var/log/sysstat/sar$(date --date="20181227" +%Y%m%d)
00:00:01      runq-sz  plist-sz   ldavg-1   ldavg-5  ldavg-15   blocked

sadf -- -q
svr001	301	2018-12-28 23:05:01 UTC	-	runq-sz	1
svr001	301	2018-12-28 23:05:01 UTC	-	plist-sz	143
svr001	301	2018-12-28 23:05:01 UTC	-	ldavg-1	0.00
svr001	301	2018-12-28 23:05:01 UTC	-	ldavg-5	0.00
svr001	301	2018-12-28 23:05:01 UTC	-	ldavg-15	0.00
svr001	301	2018-12-28 23:05:01 UTC	-	blocked	0
svr001	600	2018-12-28 23:15:01 UTC	-	runq-sz	1
svr001	600	2018-12-28 23:15:01 UTC	-	plist-sz	143
svr001	600	2018-12-28 23:15:01 UTC	-	ldavg-1	0.00
svr001	600	2018-12-28 23:15:01 UTC	-	ldavg-5	0.00
svr001	600	2018-12-28 23:15:01 UTC	-	ldavg-15	0.00
svr001	600	2018-12-28 23:15:01 UTC	-	blocked	0
svr001	600	2018-12-28 23:25:01 UTC	-	runq-sz	2
svr001	600	2018-12-28 23:25:01 UTC	-	plist-sz	143
svr001	600	2018-12-28 23:25:01 UTC	-	ldavg-1	0.00
svr001	600	2018-12-28 23:25:01 UTC	-	ldavg-5	0.00
svr001	600	2018-12-28 23:25:01 UTC	-	ldavg-15	0.00
svr001	600	2018-12-28 23:25:01 UTC	-	blocked	0
svr001	599	2018-12-28 23:35:01 UTC	-	runq-sz	1
svr001	599	2018-12-28 23:35:01 UTC	-	plist-sz	143
svr001	599	2018-12-28 23:35:01 UTC	-	ldavg-1	0.01
svr001	599	2018-12-28 23:35:01 UTC	-	ldavg-5	0.00
svr001	599	2018-12-28 23:35:01 UTC	-	ldavg-15	0.00
svr001	599	2018-12-28 23:35:01 UTC	-	blocked	0

**Comment by desbma** [comment]
OK, so you have data to plot, but gnuplot fails to parse it.

Given the ```gnuplot> set decimalsign locale;
^
line 0: Could not find requested locale```
error message, I'd say gnuplot does not recognize the decimal seprator from your locale.

Can you give the output of:
* `sadf -d -U -- -q | tail`
* `echo $LANG`

I my theory is right, you should be able to run `sysstat_report` by setting a dummy locale, ie with:
`LANG=C sysstat_report.py daily ...`. If that works, that means something something is wrong with your system because some locale files are missing, or the locale is not set, see here for more info: https://wiki.debian.org/Locale.

**Comment by samhae** [comment]
Getting the same error, also with LANG=C

Here is the output:

sadf -d -U -- -q | tail
svr001;601;1546192502;2;143;0.00;0.00;0.00;0
svr001;600;1546193101;1;143;0.00;0.00;0.00;0
svr001;599;1546193701;1;142;0.00;0.00;0.00;0
svr001;600;1546194301;1;143;0.00;0.00;0.00;0
svr001;600;1546194901;1;142;0.00;0.00;0.00;0
svr001;600;1546195501;2;143;0.00;0.00;0.00;0
svr001;599;1546196101;1;142;0.00;0.00;0.00;0
svr001;601;1546196701;1;142;0.00;0.00;0.00;0
svr001;599;1546197301;2;143;0.00;0.00;0.00;0
svr001;600;1546197901;1;143;0.00;0.00;0.00;0

echo $LANG
en_US.UTF-8

**Comment by desbma** [comment]
You have a locale set, and it is definitely not an obscure one. And your decimal separator is `.` as expected in the `sadf` output.

Can you post the output of: `echo 'set decimalsign locale' | gnuplot`? If you get the same `Could not find requested locale` warning, it is likely a gnuplot bug, you can then open a bug for the Debian package with that command to reproduce the issue.

**Comment by samhae** [comment]
You were right, thank you for the support. I'll open a bug.

gnuplot> set decimalsign locale
                         ^
         line 0: Could not find requested locale
